CREATE ROLE super WITH LOGIN PASSWORD '123qwe';

CREATE ROLE producto WITH LOGIN PASSWORD 'producto123qwe' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE producto_database;
GRANT ALL PRIVILEGES ON DATABASE producto_database TO producto ;
GRANT ALL PRIVILEGES ON DATABASE producto_database TO super;

CREATE ROLE proveedor_cliente WITH LOGIN PASSWORD 'proveedor123qwe' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE proveedor_cliente_database;
GRANT ALL PRIVILEGES ON DATABASE proveedor_cliente_database TO proveedor_cliente ;
GRANT ALL PRIVILEGES ON DATABASE proveedor_cliente_database TO super;

CREATE ROLE usuario WITH LOGIN PASSWORD 'usuario123qwe' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE usuario_database;
GRANT ALL PRIVILEGES ON DATABASE usuario_database TO usuario ;
GRANT ALL PRIVILEGES ON DATABASE usuario_database TO super;

CREATE ROLE facturacion WITH LOGIN PASSWORD 'facturacion123qwe' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE facturacion_database;
GRANT ALL PRIVILEGES ON DATABASE facturacion_database TO usuario ;
GRANT ALL PRIVILEGES ON DATABASE facturacion_database TO super;